name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Push to server
        uses: appleboy/ssh-action@master
        env:
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          CORS: ${{ secrets.CORS }}
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          PASSWORD: ${{ secrets.PASSWORD }}
          envs: EMAIL,EMAIL_PASSWORD,CORS,COOKIE_SECRET
          script: cd ${{ secrets.PATH }} && git pull && npm i && npm i -D && EMAIL=$EMAIL EMAIL_PASSWORD=$EMAIL_PASSWORD CORS=$CORS COOKIE_SECRET=$COOKIE_SECRET npm run deploy
